// <auto-generated />
using System;
using EstruplastERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstruplastERP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230161315_AjusteFamilias")]
    partial class AjusteFamilias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstruplastERP.Core.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EstruplastERP.Core.ClienteMaterialFazon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialGenericoId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialRealId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MaterialGenericoId");

                    b.HasIndex("MaterialRealId");

                    b.ToTable("ClientesMaterialesFazon");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadKilos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaId");

                    b.HasIndex("OrdenProduccionId");

                    b.ToTable("ConsumosOrdenes");
                });

            modelBuilder.Entity("EstruplastERP.Core.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DNI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puesto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Formulas");

                    b.HasData(
                        new
                        {
                            Id = 50,
                            Cantidad = 100m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 900
                        },
                        new
                        {
                            Id = 51,
                            Cantidad = 100m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 901
                        },
                        new
                        {
                            Id = 52,
                            Cantidad = 98m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 902
                        },
                        new
                        {
                            Id = 53,
                            Cantidad = 2m,
                            MateriaPrimaId = 22,
                            ProductoTerminadoId = 902
                        },
                        new
                        {
                            Id = 54,
                            Cantidad = 98m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 903
                        },
                        new
                        {
                            Id = 55,
                            Cantidad = 2m,
                            MateriaPrimaId = 22,
                            ProductoTerminadoId = 903
                        },
                        new
                        {
                            Id = 56,
                            Cantidad = 100m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 904
                        },
                        new
                        {
                            Id = 57,
                            Cantidad = 100m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 905
                        },
                        new
                        {
                            Id = 58,
                            Cantidad = 100m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 906
                        },
                        new
                        {
                            Id = 59,
                            Cantidad = 100m,
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 907
                        },
                        new
                        {
                            Id = 60,
                            Cantidad = 100m,
                            MateriaPrimaId = 991,
                            ProductoTerminadoId = 908
                        },
                        new
                        {
                            Id = 61,
                            Cantidad = 100m,
                            MateriaPrimaId = 992,
                            ProductoTerminadoId = 909
                        },
                        new
                        {
                            Id = 62,
                            Cantidad = 100m,
                            MateriaPrimaId = 992,
                            ProductoTerminadoId = 910
                        },
                        new
                        {
                            Id = 63,
                            Cantidad = 100m,
                            MateriaPrimaId = 993,
                            ProductoTerminadoId = 911
                        },
                        new
                        {
                            Id = 70,
                            Cantidad = 100m,
                            MateriaPrimaId = 602,
                            ProductoTerminadoId = 106
                        },
                        new
                        {
                            Id = 71,
                            Cantidad = 100m,
                            MateriaPrimaId = 602,
                            ProductoTerminadoId = 107
                        });
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoteProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroRemito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Turno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KilosEstimados")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kilos")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ancho")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoSku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsFazon")
                        .HasColumnType("bit");

                    b.Property<bool>("EsGenerico")
                        .HasColumnType("bit");

                    b.Property<bool>("EsMateriaPrima")
                        .HasColumnType("bit");

                    b.Property<bool>("EsProductoTerminado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Espesor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EspesorMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EspesorMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Largo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PesoEspecifico")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoPadreId")
                        .HasColumnType("int");

                    b.Property<string>("Rubro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoPadreId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-FAZON-GEN",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2421),
                            Largo = 0m,
                            Nombre = "MATERIAL DE CLIENTE (GENÉRICO)",
                            PesoEspecifico = 1.00m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 990,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-FAZ-AI",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 10,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2425),
                            Largo = 0m,
                            Nombre = "MP FAZÓN ALTO IMPACTO (BASE)",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 991,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-FAZ-ABS",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 20,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2428),
                            Largo = 0m,
                            Nombre = "MP FAZÓN ABS (BASE)",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 992,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-FAZ-PP",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 30,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2432),
                            Largo = 0m,
                            Nombre = "MP FAZÓN POLIPROPILENO (BASE)",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 993,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-FAZ-PE",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 40,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2436),
                            Largo = 0m,
                            Nombre = "MP FAZÓN PEAD/PEBD (BASE)",
                            PesoEspecifico = 0.96m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MB-COL",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 50,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2439),
                            Largo = 0m,
                            Nombre = "Masterbatch Color (Varios)",
                            PesoEspecifico = 1.20m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 600,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "REC-AI-BLA",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 10,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2443),
                            Largo = 0m,
                            Nombre = "SCRAP A.I. BLANCO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA RECUPERADA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 601,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "REC-AI-NEG",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 10,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2447),
                            Largo = 0m,
                            Nombre = "SCRAP A.I. NEGRO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA RECUPERADA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 602,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "REC-AI-TUT",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 10,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2450),
                            Largo = 0m,
                            Nombre = "A.I. TUTTI (MEZCLA)",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA RECUPERADA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 603,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "REC-PP",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 30,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2453),
                            Largo = 0m,
                            Nombre = "SCRAP PP",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA RECUPERADA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 604,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "REC-PEAD",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 40,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2456),
                            Largo = 0m,
                            Nombre = "SCRAP PEAD",
                            PesoEspecifico = 0.96m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA RECUPERADA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 605,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "REC-ABS",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FamiliaId = 20,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2459),
                            Largo = 0m,
                            Nombre = "SCRAP ABS",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA RECUPERADA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-FINO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2466),
                            Largo = 0m,
                            Nombre = "A.I. FINO (0.40 - 0.90 mm)",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 102,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-FINO-COL",
                            Color = "A Elección",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2471),
                            Largo = 0m,
                            Nombre = "A.I. FINO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 106,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-TUTTI-FINO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2475),
                            Largo = 0m,
                            Nombre = "A.I. TUTTI FINO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 101,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-GRUESO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2479),
                            Largo = 0m,
                            Nombre = "A.I. GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 103,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-GRUESO-COL",
                            Color = "A Elección",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2483),
                            Largo = 0m,
                            Nombre = "A.I. GRUESO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 104,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-BICAPA",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2486),
                            Largo = 0m,
                            Nombre = "A.I. BICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 105,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-TRICAPA",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2490),
                            Largo = 0m,
                            Nombre = "A.I. TRICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 107,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-TUTTI-GRUESO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2494),
                            Largo = 0m,
                            Nombre = "A.I. TUTTI GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 108,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-FREON",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2497),
                            Largo = 0m,
                            Nombre = "A.I. RESISTENTE AL FREON",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 109,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "AI-FREON-COL",
                            Color = "A Elección",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2589),
                            Largo = 0m,
                            Nombre = "A.I. RESISTENTE AL FREON COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 200,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "ABS-BLA",
                            Color = "Blanco",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2593),
                            Largo = 0m,
                            Nombre = "ABS BLANCO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 201,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "ABS-COL",
                            Color = "A Elección",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2597),
                            Largo = 0m,
                            Nombre = "ABS COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 202,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "ABS-GRUESO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 1.00m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2600),
                            Largo = 0m,
                            Nombre = "ABS GRUESO (Min 1mm)",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 300,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "PP-STD",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2604),
                            Largo = 0m,
                            Nombre = "PP (POLIPROPILENO)",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 301,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "PP-COL",
                            Color = "A Elección",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2609),
                            Largo = 0m,
                            Nombre = "PP COLOR",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 400,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "PE-MIX",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2613),
                            Largo = 0m,
                            Nombre = "PEAD / PEBD",
                            PesoEspecifico = 0.94m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 401,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "PEBD-GOF",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2617),
                            Largo = 0m,
                            Nombre = "PEBD GOFRADO",
                            PesoEspecifico = 0.92m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 402,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "PEAD-BIC",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2620),
                            Largo = 0m,
                            Nombre = "PEAD BICAPA",
                            PesoEspecifico = 0.96m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 500,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "BIO-LAM",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2624),
                            Largo = 0m,
                            Nombre = "BIOPLASTICO",
                            PesoEspecifico = 1.25m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 900,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-FIN",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2629),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. FINO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 902,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-FIN-COL",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2634),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. FINO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 906,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-TUT-FIN",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2638),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. TUTTI FINO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 909,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-POLI-FIN",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2642),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - PEAD/PP/BIO FINO",
                            PesoEspecifico = 0.95m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 901,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2645),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 903,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-GRU-COL",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2649),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. GRUESO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 904,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-BIC",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2653),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. BICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 905,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-TRI",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2658),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. TRICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 907,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-AI-TUT-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2662),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - A.I. TUTTI GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 908,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-ABS-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2667),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - ABS GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 910,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-POLI-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2671),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - PEAD/PP/BIO GRUESO",
                            PesoEspecifico = 0.95m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 911,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "FAZ-PEAD-BIC",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2025, 12, 30, 13, 13, 14, 511, DateTimeKind.Local).AddTicks(2675),
                            Largo = 0m,
                            Nombre = "LAMINADO A FAZON - PEAD BICAPA",
                            PesoEspecifico = 0.96m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        });
                });

            modelBuilder.Entity("EstruplastERP.Core.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ContactoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroRemito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Remitos");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitarioSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("RemitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("RemitoDetalles");
                });

            modelBuilder.Entity("EstruplastERP.Core.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstruplastERP.Core.ClienteMaterialFazon", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "MaterialGenerico")
                        .WithMany()
                        .HasForeignKey("MaterialGenericoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "MaterialReal")
                        .WithMany()
                        .HasForeignKey("MaterialRealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("MaterialGenerico");

                    b.Navigation("MaterialReal");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoOrden", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EstruplastERP.Core.OrdenProduccion", "OrdenProduccion")
                        .WithMany("Consumos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("OrdenProduccion");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "ProductoTerminado")
                        .WithMany("Formulas")
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("ProductoTerminado");
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EstruplastERP.Core.Producto", "ProductoPadre")
                        .WithMany()
                        .HasForeignKey("ProductoPadreId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("ProductoPadre");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Remito", "Remito")
                        .WithMany("Detalles")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("EstruplastERP.Core.Usuario", b =>
                {
                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Navigation("Formulas");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
