// <auto-generated />
using System;
using EstruplastERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstruplastERP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218172815_RangoEspesores")]
    partial class RangoEspesores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstruplastERP.Core.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadKilos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaId");

                    b.HasIndex("OrdenProduccionId");

                    b.ToTable("ConsumosOrdenes");
                });

            modelBuilder.Entity("EstruplastERP.Core.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DNI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puesto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Formulas");

                    b.HasData(
                        new
                        {
                            Id = 200,
                            Cantidad = 96m,
                            MateriaPrimaId = 1,
                            ProductoTerminadoId = 50
                        },
                        new
                        {
                            Id = 201,
                            Cantidad = 4m,
                            MateriaPrimaId = 8,
                            ProductoTerminadoId = 50
                        },
                        new
                        {
                            Id = 202,
                            Cantidad = 98m,
                            MateriaPrimaId = 1,
                            ProductoTerminadoId = 51
                        },
                        new
                        {
                            Id = 203,
                            Cantidad = 2m,
                            MateriaPrimaId = 9,
                            ProductoTerminadoId = 51
                        },
                        new
                        {
                            Id = 204,
                            Cantidad = 100m,
                            MateriaPrimaId = 3,
                            ProductoTerminadoId = 70
                        },
                        new
                        {
                            Id = 215,
                            Cantidad = 100m,
                            MateriaPrimaId = 1,
                            ProductoTerminadoId = 52
                        });
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoteProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroRemito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Turno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KilosEstimados")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kilos")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ancho")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoSku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsGenerico")
                        .HasColumnType("bit");

                    b.Property<bool>("EsMateriaPrima")
                        .HasColumnType("bit");

                    b.Property<bool>("EsProductoTerminado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Espesor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EspesorMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EspesorMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Largo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PesoEspecifico")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoPadreId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoPadreId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PAI",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2388),
                            Largo = 0m,
                            Nombre = "Poliestireno Alto Impacto (AI/PAI)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            StockActual = 1000m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-ABS",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2393),
                            Largo = 0m,
                            Nombre = "ABS (Acrilonitrilo Butadieno Estireno)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            StockActual = 1000m,
                            StockMinimo = 500m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PP",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2399),
                            Largo = 0m,
                            Nombre = "Polipropileno (PP)",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            StockActual = 1000m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PEAD",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2403),
                            Largo = 0m,
                            Nombre = "Polietileno Alta Densidad (PEAD)",
                            PesoEspecifico = 0.95m,
                            PrecioCosto = 0m,
                            StockActual = 1000m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PEBD",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2406),
                            Largo = 0m,
                            Nombre = "Polietileno Baja Densidad (PEBD)",
                            PesoEspecifico = 0.92m,
                            PrecioCosto = 0m,
                            StockActual = 1000m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-BIO",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2410),
                            Largo = 0m,
                            Nombre = "Bioplástico Compostable (Biolam)",
                            PesoEspecifico = 1.25m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 200m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-BLA",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2413),
                            Largo = 0m,
                            Nombre = "Masterbatch Blanco (Titanio)",
                            PesoEspecifico = 1.80m,
                            PrecioCosto = 0m,
                            StockActual = 500m,
                            StockMinimo = 100m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-NEG",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2416),
                            Largo = 0m,
                            Nombre = "Masterbatch Negro",
                            PesoEspecifico = 1.20m,
                            PrecioCosto = 0m,
                            StockActual = 500m,
                            StockMinimo = 100m
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-ADITIVO-GEN",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2419),
                            Largo = 0m,
                            Nombre = "Aditivo Genérico",
                            PesoEspecifico = 0.95m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 50m
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-ROJ",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2422),
                            Largo = 0m,
                            Nombre = "Masterbatch Rojo",
                            PesoEspecifico = 1.20m,
                            PrecioCosto = 0m,
                            StockActual = 100m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-AZU",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2425),
                            Largo = 0m,
                            Nombre = "Masterbatch Azul",
                            PesoEspecifico = 1.20m,
                            PrecioCosto = 0m,
                            StockActual = 100m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-VER",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2428),
                            Largo = 0m,
                            Nombre = "Masterbatch Verde",
                            PesoEspecifico = 1.20m,
                            PrecioCosto = 0m,
                            StockActual = 100m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-AMA",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2431),
                            Largo = 0m,
                            Nombre = "Masterbatch Amarillo",
                            PesoEspecifico = 1.20m,
                            PrecioCosto = 0m,
                            StockActual = 100m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-BRILLO",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2434),
                            Largo = 0m,
                            Nombre = "Aditivo Brillo",
                            PesoEspecifico = 0.92m,
                            PrecioCosto = 0m,
                            StockActual = 500m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-ESTEARATO",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2436),
                            Largo = 0m,
                            Nombre = "Estearato de Zinc",
                            PesoEspecifico = 0.35m,
                            PrecioCosto = 0m,
                            StockActual = 200m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-CARGA",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2439),
                            Largo = 0m,
                            Nombre = "Carga Mineral (Carbonato)",
                            PesoEspecifico = 1.80m,
                            PrecioCosto = 0m,
                            StockActual = 2000m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-UV",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2442),
                            Largo = 0m,
                            Nombre = "Aditivo UV",
                            PesoEspecifico = 0.95m,
                            PrecioCosto = 0m,
                            StockActual = 200m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-CAUCHO",
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2445),
                            Largo = 0m,
                            Nombre = "Aditivo Caucho",
                            PesoEspecifico = 0.94m,
                            PrecioCosto = 0m,
                            StockActual = 200m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 50,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PAI-B",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2448),
                            Largo = 0m,
                            Nombre = "Material PAI Blanco",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 500m
                        },
                        new
                        {
                            Id = 51,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PAI-N",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2451),
                            Largo = 0m,
                            Nombre = "Material PAI Negro",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 500m
                        },
                        new
                        {
                            Id = 52,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PAI-C",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2454),
                            Largo = 0m,
                            Nombre = "Material PAI Color",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 200m
                        },
                        new
                        {
                            Id = 53,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PAI-BIC",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2457),
                            Largo = 0m,
                            Nombre = "Material PAI Bicapa",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 500m
                        },
                        new
                        {
                            Id = 54,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PAI-TRI",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2526),
                            Largo = 0m,
                            Nombre = "Material PAI Tricapa",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 500m
                        },
                        new
                        {
                            Id = 60,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-ABS-B",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2529),
                            Largo = 0m,
                            Nombre = "Material ABS Blanco",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 300m
                        },
                        new
                        {
                            Id = 61,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-ABS-C",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2532),
                            Largo = 0m,
                            Nombre = "Material ABS Negro/Color",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 300m
                        },
                        new
                        {
                            Id = 70,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PP",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2534),
                            Largo = 0m,
                            Nombre = "Material PP",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 80,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PEAD",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2538),
                            Largo = 0m,
                            Nombre = "Material PEAD",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 81,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-PEBD",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2540),
                            Largo = 0m,
                            Nombre = "Material PEBD",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 90,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MAT-BIO",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2543),
                            Largo = 0m,
                            Nombre = "Material Biolam",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 200m
                        },
                        new
                        {
                            Id = 99,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "REV-PET",
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2546),
                            Largo = 0m,
                            Nombre = "Lámina PET (Reventa)",
                            PesoEspecifico = 0m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 500m
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-PAI-1000-05",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2549),
                            Largo = 2000m,
                            Nombre = "Lámina PAI Blanco 1000x2000x0.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 50,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 101,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-PAI-1000-10",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2555),
                            Largo = 2000m,
                            Nombre = "Lámina PAI Blanco 1000x2000x1.0 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 50,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 102,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-PAI-1000-15",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2559),
                            Largo = 2000m,
                            Nombre = "Lámina PAI Blanco 1000x2000x1.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 50,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 103,
                            Activo = true,
                            Ancho = 1220m,
                            CodigoSku = "STD-PAI-1220-05",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2563),
                            Largo = 2440m,
                            Nombre = "Lámina PAI Blanco 1220x2440x0.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 50,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 104,
                            Activo = true,
                            Ancho = 1220m,
                            CodigoSku = "STD-PAI-1220-10",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2568),
                            Largo = 2440m,
                            Nombre = "Lámina PAI Blanco 1220x2440x1.0 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 50,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 105,
                            Activo = true,
                            Ancho = 1220m,
                            CodigoSku = "STD-PAI-1220-15",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2572),
                            Largo = 2440m,
                            Nombre = "Lámina PAI Blanco 1220x2440x1.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 50,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 110,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-BIC-1000-10",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2576),
                            Largo = 2000m,
                            Nombre = "Lámina PAI Bicapa 1000x2000x1.0 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 53,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 111,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-BIC-1000-15",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2580),
                            Largo = 2000m,
                            Nombre = "Lámina PAI Bicapa 1000x2000x1.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 53,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 112,
                            Activo = true,
                            Ancho = 1220m,
                            CodigoSku = "STD-BIC-1220-10",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2583),
                            Largo = 2440m,
                            Nombre = "Lámina PAI Bicapa 1220x2440x1.0 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 53,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 113,
                            Activo = true,
                            Ancho = 1220m,
                            CodigoSku = "STD-BIC-1220-15",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2587),
                            Largo = 2440m,
                            Nombre = "Lámina PAI Bicapa 1220x2440x1.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 53,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 120,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-TRI-1000-10",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2591),
                            Largo = 2000m,
                            Nombre = "Lámina PAI Tricapa 1000x2000x1.0 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 54,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 121,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-TRI-1000-15",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2595),
                            Largo = 2000m,
                            Nombre = "Lámina PAI Tricapa 1000x2000x1.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 54,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 122,
                            Activo = true,
                            Ancho = 1220m,
                            CodigoSku = "STD-TRI-1220-10",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.0m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2599),
                            Largo = 2440m,
                            Nombre = "Lámina PAI Tricapa 1220x2440x1.0 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 54,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 123,
                            Activo = true,
                            Ancho = 1220m,
                            CodigoSku = "STD-TRI-1220-15",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.5m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2603),
                            Largo = 2440m,
                            Nombre = "Lámina PAI Tricapa 1220x2440x1.5 mm",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 54,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 130,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-PET-050",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0.50m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2607),
                            Largo = 2000m,
                            Nombre = "Lámina PET 1000x2000x0.50 mm",
                            PesoEspecifico = 1.38m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 99,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 131,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-PET-080",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0.80m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2610),
                            Largo = 2000m,
                            Nombre = "Lámina PET 1000x2000x0.80 mm",
                            PesoEspecifico = 1.38m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 99,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 132,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-PET-100",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.00m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2615),
                            Largo = 2000m,
                            Nombre = "Lámina PET 1000x2000x1.00 mm",
                            PesoEspecifico = 1.38m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 99,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 140,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-BIO-050",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0.50m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2619),
                            Largo = 2000m,
                            Nombre = "Lámina BIOLAM 1000x2000x0.50 mm",
                            PesoEspecifico = 1.25m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 90,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 141,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-BIO-070",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 0.70m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2664),
                            Largo = 2000m,
                            Nombre = "Lámina BIOLAM 1000x2000x0.70 mm",
                            PesoEspecifico = 1.25m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 90,
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 142,
                            Activo = true,
                            Ancho = 1000m,
                            CodigoSku = "STD-BIO-100",
                            EsGenerico = false,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            Espesor = 1.00m,
                            FechaCreacion = new DateTime(2025, 12, 18, 14, 28, 13, 961, DateTimeKind.Local).AddTicks(2668),
                            Largo = 2000m,
                            Nombre = "Lámina BIOLAM 1000x2000x1.00 mm",
                            PesoEspecifico = 1.25m,
                            PrecioCosto = 0m,
                            ProductoPadreId = 90,
                            StockActual = 0m,
                            StockMinimo = 0m
                        });
                });

            modelBuilder.Entity("EstruplastERP.Core.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ContactoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroRemito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Remitos");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitarioSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("RemitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("RemitoDetalles");
                });

            modelBuilder.Entity("EstruplastERP.Core.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoOrden", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EstruplastERP.Core.OrdenProduccion", "OrdenProduccion")
                        .WithMany("Consumos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("OrdenProduccion");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "ProductoTerminado")
                        .WithMany("Formulas")
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("ProductoTerminado");
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EstruplastERP.Core.Producto", "ProductoPadre")
                        .WithMany()
                        .HasForeignKey("ProductoPadreId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("ProductoPadre");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Remito", "Remito")
                        .WithMany("Detalles")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("EstruplastERP.Core.Usuario", b =>
                {
                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Navigation("Formulas");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
