// <auto-generated />
using System;
using EstruplastERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstruplastERP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251211164609_correccionPAi")]
    partial class correccionPAi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstruplastERP.Core.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EstruplastERP.Core.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DNI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puesto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Turno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoSku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsMateriaPrima")
                        .HasColumnType("bit");

                    b.Property<bool>("EsProductoTerminado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Espesor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Largo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PesoEspecifico")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PAI",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2954),
                            Largo = 0m,
                            Nombre = "Poliestireno Alto Impacto (AI/PAI)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-ABS",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2958),
                            Largo = 0m,
                            Nombre = "ABS (Acrilonitrilo Butadieno Estireno)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 500m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PP",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2962),
                            Largo = 0m,
                            Nombre = "Polipropileno (PP)",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PEAD",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2965),
                            Largo = 0m,
                            Nombre = "Polietileno Alta Densidad (PEAD)",
                            PesoEspecifico = 0.95m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-PEBD",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2968),
                            Largo = 0m,
                            Nombre = "Polietileno Baja Densidad (PEBD)",
                            PesoEspecifico = 0.92m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 1000m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-BIO",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2971),
                            Largo = 0m,
                            Nombre = "Bioplástico Compostable (Biolam)",
                            PesoEspecifico = 1.25m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 200m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-BLA",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2974),
                            Largo = 0m,
                            Nombre = "Masterbatch Blanco (Titanio)",
                            PesoEspecifico = 1.80m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 100m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-MST-NEG",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2978),
                            Largo = 0m,
                            Nombre = "Masterbatch Negro",
                            PesoEspecifico = 1.20m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 100m
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Ancho = 0m,
                            CodigoSku = "MP-ADITIVO",
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            Espesor = 0m,
                            FechaCreacion = new DateTime(2025, 12, 11, 13, 46, 8, 470, DateTimeKind.Local).AddTicks(2982),
                            Largo = 0m,
                            Nombre = "Aditivo UV / Caucho",
                            PesoEspecifico = 0.95m,
                            PrecioCosto = 0m,
                            StockActual = 0m,
                            StockMinimo = 50m
                        });
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroRemito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Remitos");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("RemitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("RemitoDetalles");
                });

            modelBuilder.Entity("EstruplastERP.Core.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", null)
                        .WithMany("Formulas")
                        .HasForeignKey("ProductoId");

                    b.HasOne("EstruplastERP.Core.Producto", "ProductoTerminado")
                        .WithMany()
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("ProductoTerminado");
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Remito", "Remito")
                        .WithMany("Detalles")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("EstruplastERP.Core.Usuario", b =>
                {
                    b.HasOne("EstruplastERP.Core.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Navigation("Formulas");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
