// <auto-generated />
using System;
using EstruplastERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstruplastERP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstruplastERP.Core.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsFazon")
                        .HasColumnType("bit");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EstruplastERP.Core.ClienteMaterialFazon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialGenericoId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialRealId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MaterialGenericoId");

                    b.HasIndex("MaterialRealId");

                    b.ToTable("ClientesMaterialesFazon");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoHojaCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRealKg")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("HojaCargaId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HojaCargaId");

                    b.HasIndex("MateriaPrimaId");

                    b.ToTable("ConsumosHojasCarga");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadKilos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaId");

                    b.HasIndex("OrdenProduccionId");

                    b.ToTable("ConsumosOrdenes");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ExtrusoraDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MateriaPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrimaId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Formulas");

                    b.HasData(
                        new
                        {
                            Id = 50,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 900
                        },
                        new
                        {
                            Id = 51,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 901
                        },
                        new
                        {
                            Id = 52,
                            Cantidad = 98m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 902
                        },
                        new
                        {
                            Id = 53,
                            Cantidad = 2m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 22,
                            ProductoTerminadoId = 902
                        },
                        new
                        {
                            Id = 54,
                            Cantidad = 98m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 903
                        },
                        new
                        {
                            Id = 55,
                            Cantidad = 2m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 22,
                            ProductoTerminadoId = 903
                        },
                        new
                        {
                            Id = 56,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 904
                        },
                        new
                        {
                            Id = 57,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 905
                        },
                        new
                        {
                            Id = 58,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 906
                        },
                        new
                        {
                            Id = 59,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 990,
                            ProductoTerminadoId = 907
                        },
                        new
                        {
                            Id = 60,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 991,
                            ProductoTerminadoId = 908
                        },
                        new
                        {
                            Id = 63,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 993,
                            ProductoTerminadoId = 911
                        },
                        new
                        {
                            Id = 64,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 994,
                            ProductoTerminadoId = 912
                        },
                        new
                        {
                            Id = 65,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 994,
                            ProductoTerminadoId = 913
                        },
                        new
                        {
                            Id = 66,
                            Cantidad = 100m,
                            ExtrusoraDestino = "UNICA",
                            MateriaPrimaId = 994,
                            ProductoTerminadoId = 914
                        });
                });

            modelBuilder.Entity("EstruplastERP.Core.HojaCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDeclaracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HojasCarga");
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroRemito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OrdenProduccionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OrdenProduccionId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AditivoUV")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConBrillo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Desperdicio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsBobina")
                        .HasColumnType("bit");

                    b.Property<bool>("EsGofrado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsImpreso")
                        .HasColumnType("bit");

                    b.Property<decimal>("Espesor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HojaCargaId")
                        .HasColumnType("int");

                    b.Property<decimal>("KilosEstimados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Largo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LlevaFilm")
                        .HasColumnType("bit");

                    b.Property<string>("NotaPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCorona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HojaCargaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("EstruplastERP.Core.PalletProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroPallet")
                        .HasColumnType("int");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenProduccionId");

                    b.ToTable("PalletsProduccion");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kilos")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoTerminadoId")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EsFazon")
                        .HasColumnType("bit");

                    b.Property<bool>("EsGenerico")
                        .HasColumnType("bit");

                    b.Property<bool>("EsMateriaPrima")
                        .HasColumnType("bit");

                    b.Property<bool>("EsProductoTerminado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsScrap")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EspesorMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EspesorMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PesoEspecifico")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("Rubro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            Activo = true,
                            CodigoSku = "MP-FAZON-GEN",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            EsScrap = false,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7172),
                            Nombre = "MATERIAL DE CLIENTE (GENÉRICO)",
                            PesoEspecifico = 1.00m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 990,
                            Activo = true,
                            CodigoSku = "MP-FAZ-AI",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            EsScrap = false,
                            FamiliaId = 10,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7177),
                            Nombre = "MP FAZÓN ALTO IMPACTO (BASE)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 991,
                            Activo = true,
                            CodigoSku = "MP-FAZ-ABS",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            EsScrap = false,
                            FamiliaId = 20,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7181),
                            Nombre = "MP FAZÓN ABS (BASE)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 992,
                            Activo = true,
                            CodigoSku = "MP-FAZ-PP",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            EsScrap = false,
                            FamiliaId = 30,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7185),
                            Nombre = "MP FAZÓN POLIPROPILENO (BASE)",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 993,
                            Activo = true,
                            CodigoSku = "MP-FAZ-PE",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            EsScrap = false,
                            FamiliaId = 40,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7188),
                            Nombre = "MP FAZÓN PEAD/PEBD (BASE)",
                            PesoEspecifico = 0.96m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 994,
                            Activo = true,
                            CodigoSku = "MP-FAZ-FREON",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            EsScrap = false,
                            FamiliaId = 60,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7191),
                            Nombre = "MP FAZÓN FREON (BASE)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CodigoSku = "MP-MB-COL",
                            EsFazon = false,
                            EsGenerico = false,
                            EsMateriaPrima = true,
                            EsProductoTerminado = false,
                            EsScrap = false,
                            FamiliaId = 50,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7195),
                            Nombre = "Masterbatch Color (Varios)",
                            PesoEspecifico = 1.1m,
                            PrecioCosto = 0m,
                            Rubro = "MATERIA PRIMA",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            CodigoSku = "AI-FINO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7201),
                            Nombre = "A.I. FINO (0.40 - 0.90 mm)",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 102,
                            Activo = true,
                            CodigoSku = "AI-FINO-COL",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7205),
                            Nombre = "A.I. FINO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 106,
                            Activo = true,
                            CodigoSku = "AI-TUTTI-FINO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7209),
                            Nombre = "A.I. TUTTI FINO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 101,
                            Activo = true,
                            CodigoSku = "AI-GRUESO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7213),
                            Nombre = "A.I. GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 103,
                            Activo = true,
                            CodigoSku = "AI-GRUESO-COL",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7217),
                            Nombre = "A.I. GRUESO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 104,
                            Activo = true,
                            CodigoSku = "AI-BICAPA",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7221),
                            Nombre = "A.I. BICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 105,
                            Activo = true,
                            CodigoSku = "AI-TRICAPA",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7225),
                            Nombre = "A.I. TRICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 107,
                            Activo = true,
                            CodigoSku = "AI-TUTTI-GRUESO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7230),
                            Nombre = "A.I. TUTTI GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 108,
                            Activo = true,
                            CodigoSku = "AI-FREON",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7236),
                            Nombre = "A.I. RESISTENTE AL FREON",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 109,
                            Activo = true,
                            CodigoSku = "AI-FREON-COL",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7240),
                            Nombre = "A.I. RESISTENTE AL FREON COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 200,
                            Activo = true,
                            CodigoSku = "ABS-BLA",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7243),
                            Nombre = "ABS BLANCO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 201,
                            Activo = true,
                            CodigoSku = "ABS-COL",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7247),
                            Nombre = "ABS COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 202,
                            Activo = true,
                            CodigoSku = "ABS-GRUESO",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 1.00m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7251),
                            Nombre = "ABS GRUESO (Min 1mm)",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 300,
                            Activo = true,
                            CodigoSku = "PP-STD",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7255),
                            Nombre = "PP (POLIPROPILENO)",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 301,
                            Activo = true,
                            CodigoSku = "PP-COL",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7259),
                            Nombre = "PP COLOR",
                            PesoEspecifico = 0.91m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 400,
                            Activo = true,
                            CodigoSku = "PE-MIX",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7263),
                            Nombre = "PEAD / PEBD",
                            PesoEspecifico = 0.94m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 401,
                            Activo = true,
                            CodigoSku = "PEBD-GOF",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7266),
                            Nombre = "PEBD GOFRADO",
                            PesoEspecifico = 0.92m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 402,
                            Activo = true,
                            CodigoSku = "PEAD-BIC",
                            EsFazon = false,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7270),
                            Nombre = "PEAD BICAPA",
                            PesoEspecifico = 0.96m,
                            PrecioCosto = 0m,
                            Rubro = "PRODUCTO TERMINADO",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 900,
                            Activo = true,
                            CodigoSku = "FAZ-AI-FIN",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7275),
                            Nombre = "FAZON - A.I. FINO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 902,
                            Activo = true,
                            CodigoSku = "FAZ-AI-FIN-COL",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7280),
                            Nombre = "FAZON - A.I. FINO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 906,
                            Activo = true,
                            CodigoSku = "FAZ-AI-TUT-FIN",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7345),
                            Nombre = "FAZON - A.I. TUTTI FINO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 901,
                            Activo = true,
                            CodigoSku = "FAZ-AI-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7349),
                            Nombre = "FAZON - A.I. GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 903,
                            Activo = true,
                            CodigoSku = "FAZ-AI-GRU-COL",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7353),
                            Nombre = "FAZON - A.I. GRUESO COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 904,
                            Activo = true,
                            CodigoSku = "FAZ-AI-BIC",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7357),
                            Nombre = "FAZON - A.I. BICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 905,
                            Activo = true,
                            CodigoSku = "FAZ-AI-TRI",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7361),
                            Nombre = "FAZON - A.I. TRICAPA",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 907,
                            Activo = true,
                            CodigoSku = "FAZ-AI-TUT-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7366),
                            Nombre = "FAZON - A.I. TUTTI GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 908,
                            Activo = true,
                            CodigoSku = "FAZ-ABS-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7370),
                            Nombre = "FAZON - ABS GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 911,
                            Activo = true,
                            CodigoSku = "FAZ-PEAD-BIC",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7374),
                            Nombre = "FAZON - PEAD BICAPA",
                            PesoEspecifico = 0.96m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 912,
                            Activo = true,
                            CodigoSku = "FAZ-FREON-FIN",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0.90m,
                            EspesorMinimo = 0.40m,
                            FamiliaId = 60,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7378),
                            Nombre = "FAZON - RESISTENTE FREON FINO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 913,
                            Activo = true,
                            CodigoSku = "FAZ-FREON-GRU",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FamiliaId = 60,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7382),
                            Nombre = "FAZON - RESISTENTE FREON GRUESO",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        },
                        new
                        {
                            Id = 914,
                            Activo = true,
                            CodigoSku = "FAZ-FREON-COL",
                            EsFazon = true,
                            EsGenerico = true,
                            EsMateriaPrima = false,
                            EsProductoTerminado = true,
                            EsScrap = false,
                            EspesorMaximo = 0m,
                            EspesorMinimo = 0.90m,
                            FamiliaId = 60,
                            FechaCreacion = new DateTime(2026, 8, 11, 16, 54, 18, 232, DateTimeKind.Local).AddTicks(7386),
                            Nombre = "FAZON - RESISTENTE FREON COLOR",
                            PesoEspecifico = 1.05m,
                            PrecioCosto = 0m,
                            Rubro = "SERVICIO FAZON",
                            StockActual = 0m,
                            StockMinimo = 0m
                        });
                });

            modelBuilder.Entity("EstruplastERP.Core.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ContactoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroRemito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Remitos");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitarioSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("RemitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("RemitoDetalles");
                });

            modelBuilder.Entity("EstruplastERP.Core.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstruplastERP.Core.ClienteMaterialFazon", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "MaterialGenerico")
                        .WithMany()
                        .HasForeignKey("MaterialGenericoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "MaterialReal")
                        .WithMany()
                        .HasForeignKey("MaterialRealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("MaterialGenerico");

                    b.Navigation("MaterialReal");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoHojaCarga", b =>
                {
                    b.HasOne("EstruplastERP.Core.HojaCarga", "HojaCarga")
                        .WithMany("ConsumosReales")
                        .HasForeignKey("HojaCargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaCarga");

                    b.Navigation("MateriaPrima");
                });

            modelBuilder.Entity("EstruplastERP.Core.ConsumoOrden", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EstruplastERP.Core.OrdenProduccion", "OrdenProduccion")
                        .WithMany("Consumos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("OrdenProduccion");
                });

            modelBuilder.Entity("EstruplastERP.Core.Formula", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Producto", "ProductoTerminado")
                        .WithMany("Formulas")
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MateriaPrima");

                    b.Navigation("ProductoTerminado");
                });

            modelBuilder.Entity("EstruplastERP.Core.Movimiento", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.OrdenProduccion", "OrdenProduccion")
                        .WithMany()
                        .HasForeignKey("OrdenProduccionId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Cliente");

                    b.Navigation("OrdenProduccion");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.HojaCarga", "HojaCarga")
                        .WithMany("Ordenes")
                        .HasForeignKey("HojaCargaId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("HojaCarga");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.PalletProduccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.OrdenProduccion", "OrdenProduccion")
                        .WithMany("Pallets")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenProduccion");
                });

            modelBuilder.Entity("EstruplastERP.Core.Produccion", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EstruplastERP.Core.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.HasOne("EstruplastERP.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EstruplastERP.Core.RemitoDetalle", b =>
                {
                    b.HasOne("EstruplastERP.Core.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstruplastERP.Core.Remito", "Remito")
                        .WithMany("Detalles")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("EstruplastERP.Core.HojaCarga", b =>
                {
                    b.Navigation("ConsumosReales");

                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("EstruplastERP.Core.OrdenProduccion", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("EstruplastERP.Core.Producto", b =>
                {
                    b.Navigation("Formulas");
                });

            modelBuilder.Entity("EstruplastERP.Core.Remito", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
